### ISSUE TITLE
What SFS files to use

### ISSUE THREAD

**Issue by anita-wray** [xiaoming-liu/stairway-plot-v2#19]
I am working with RADseq data, so I am using easySFS to produce my SFS files. I'm confused about which ones to use for the .blueprint file. easySFS produces files in fastsimcoal and dadi format. Below is the MAFpop0.obs file, which seems like the most logical SFS but I keep getting errors that my number of sequences is too large. I'm usually 1 sequence over the nseq/2 rule. Any help would be greatly appreciated!

1 observation
d0_0	d0_1	d0_2	d0_3	d0_4	d0_5	d0_6	d0_7	d0_8	d0_9	d0_10	d0_11	d0_12	d0_13	d0_14	d0_15	d0_16	d0_17	d0_18	d0_19	d0_20	d0_21	d0_22	d0_23	d0_24	d0_25	d0_26	d0_27	d0_28
636 1065 1269 1271 1141 1003 858 786 718 688 645 628 592 601 301 0 0 0 0 0 0 0 0 0 0 0 0 0 0

**Comment by Robb-ED** [comment]
@anita-wray - just wondering if you managed to sort out what sfs to use from easysfs? I'm also using the same approach on my RAD data, and am not sure what values I should drop.

**Comment by Elevensyl** [comment]
I have the save question，should we keep 0 value when write the blueprint file?
