### ISSUE TITLE
SFS number from ANGSD not n-1..?

### ISSUE THREAD

**Issue by cistarsa** [xiaoming-liu/stairway-plot-v2#4]
Hello and thank you for this nifty program. I'm looking at recent changes in demographic history for two recently diverged populations (n=25) from an unfolded sfs spectra generated in ANGSD and realSFS as:

```bash

# angsd run for saf output:
./angsd/angsd -nThreads 28 -b WI_bam.list -out WI_angsd_sfs -doSaf 1 -minMapQ 1 -minQ 20 -GL 1 -anc F_Kansas_60.fasta

## sfs reconstruction using largest chromosome ~60MB
./angsd/misc/realSFS WI_angsd_sfs.saf.idx -r F_KS_P_RNA_scaffold_9 > WI_angsd_sfs_scaff9

``` 

However, the output from the realsfs command gives me 51 (2n+1) SFS not 49 (2n-1), which is consistent with the [doc](http://www.popgen.dk/angsd/index.php/SFS_Estimation#Brief_Overview)

 any suggestions on how to generate SFS that can be used by your program? Thank you!

**Comment by LZarri** [comment]
Hello, I'm experiencing the same issue, did you drop the first two values or the first value and the last value? Thanks so much

**Comment by xuefenfei712** [comment]
Hello, @xiaoming-liu, here you mean that the first and last number of sfs should be trash?
Thankyou
