### ISSUE TITLE
inputting the SFS into stairwayplot2

### ISSUE THREAD

**Issue by selasphoruskershaw** [xiaoming-liu/stairway-plot-v2#7]
Hello,

I successfully ran easySFS on all of my populations to use for Stairwayplot2, but for each population there is an extra number.

For example, in one population's output (15 diploid individuals), I get the following, which is 31 total numbers and 16 non-zero numbers: 12875322 432991 274827 201109 139712 107003 107935 72349 62181 58143 56489 56319 57759 62285 77825 75672 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

How do I enter these values into Stairwayplot2? I have 15 individuals and the software forces me to have 15 numbers (nseq/2) inputted for the SFS.

Thank you for your help!

**Comment by vanessaiza** [comment]
Hello, can you solve this issue?
